# vim:sw=2:et:

sudo: false
language: erlang
notifications:
  email:
    - alerts@rabbitmq.com
addons:
  apt:
    packages:
      - awscli
      - xsltproc
cache:
  apt: true
env:
  global:
    - secure: AmSdv8VNE+UVTHB50gWYv1Wd9ElczWDIiIxkh4yQEBdBHH6JT/+rQ97ev2CuNuTFHLSj5Hkv76obaKkqRm31bSu67tE10gBv2syg8pt/8Pv5q0RIFGFH/v0nrpSFUttkAqUBh5Gdi6fJSufpExPXDxtlB91jQMa9fjxYXADW/Vo=
    - secure: TINeTkWC9uBC0ifFOH5s3G0xDZV+xhnTQoz0E/1kTGveoQ6VF351vm6dHj2R2xzLd503ab/f0ojLjxuKQGQpl59clwneKIw+pF/2GAhm5fdaZkbNLBVAdmjEoOAlZADo0e9ZCq8bkG1OqU7la0rT+6idxm2z4/2VBIarptdkVtE=

otp_release:
  - "R16B03-1"
  - "19.3"
  - "20.1"

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, stable branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :

script:
  - make xref
  - make tests

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
